version: '3.2'
services:
  app:
    build: .
    expose:
      - 3000
    ports:
      - 8000:3000
    depends_on:
      - database
    environment:
      JWT_SECRET_KEY: emery_gpo_backlands_panama_cobble
      MONGOURL: mongodb://database:27017/users
    
  database:
    image: mongo
    ports:
      - 27019:27017
    volumes:
      - ./data:/data/db

  redis-server:
    image: 'redis'
